import pymongo

#Creates A New Blank Weight Class


myclient = pymongo.MongoClient("mongodb+srv://FightStatsAdmin:FightStatsAdmin716@octc1.d2he2mx.mongodb.net/?retryWrites=true&w=majority")
mydb = myclient["FightStatsDB"]
mycol = mydb["WCAV"]

mydict = { 
        "weightclassname": "Heavyweight",
        "weight":265,
        "minutes": 0, 
        "rounds": 0,
        "fights": 0,
        "kowins": 0,
        "tkowins": 0,
        "tkoloss": 0,
        "koloss": 0,
        "subwin": 0,
        "subloss": 0,
        "decwin": 0,
        "decloss": 0,
        "subattempt": 0,
        "timesknockeddown": 0,
        "numberofknockdowns": 0,
        "timesstunned": 0,
        "numberofstuns": 0,
        "AmericanaAttempts": 0,
        "AnacondaAttempt": 0,
        "AttemptedThrowTD": 0,
        "BodyKicksAbsorbed": 0,
        "BodyLockTakedownAttempts": 0,
        "BulldogAttempt": 0,
        "CalfSlicerAttempts": 0,
        "ClinchStrikeHiMake": 0,
        "ClinchStrikeLoMake": 0,
        "DoubleLegTakedownAttempts": 0,
        "EzekielAttempt": 0,
        "GogoplataAttempts": 0,
        "GroundStrikeHiMake": 0,
        "GroundStrikeLoMake": 0,
        "HooksAbsorbed": 0,
        "JabsAbsorbed": 0,
        "KneebarAttempt": 0,
        "LeftBodyKickMake": 0,
        "LeftElbowMake": 0,
        "LeftHighKickMake": 0,
        "LeftHookHiMake": 0,
        "LeftHookLoMake": 0,
        "LeftJabHiMake": 0,
        "LeftJabLoMake": 0,
        "LeftLegKickMake": 0,
        "LeftOverhandMake": 0,
        "LeftSpinBackFistMake": 0,
        "LeftStraightHiMake": 0,
        "LeftStraightLoMake": 0,
        "LeftUppercutHiMake": 0,
        "LeftUppercutLoMake": 0,
        "LegKicksAbsorbed": 0,
        "LeglockAttempt": 0,
        "LossesVsOrthodox": 0,
        "LossesVsSouthpaw": 0,
        "LossesVsSwitch": 0,
        "NeckCrankAttempt": 0,
        "OmoplataAttempt": 0,
        "OtherSubAttempt": 0,
        "OverhandsAbsorbed": 0,
        "RightBodyKickMake": 0,
        "RightElbowMake": 0,
        "RightHighKickMake": 0,
        "RightHookHiMake": 0,
        "RightHookLoMake": 0,
        "RightJabHiMake": 0,
        "RightJabLoMake": 0,
        "RightLegKickMake": 0,
        "RightOverhandMake": 0,
        "RightSpinBackFistMake": 0,
        "RightStraightHiMake": 0,
        "RightStraightLoMake": 0,
        "RightUppercutHiMake": 0,
        "RightUppercutLoMake": 0,
        "SUBRNCAttempt": 0,
        "SingleLegTakedownAttempts": 0,
        "StraightsAbsorbed": 0,
        "SubArmTriangleAttempt": 0,
        "SubAttempts": 0,
        "SubDarceAttempt": 0,
        "SubGuillotineAttempt": 0,
        "SubHeelHookAttempt": 0,
        "SubKimuraAttempt": 0,
        "SubNeckCrankAttempt": 0,
        "SubStraightArmLockAttempt": 0,
        "SubSulovStretchAttempt": 0,
        "SubTriangleArmbarAttempt": 0,
        "SubTriangleAttempt": 0,
        "TotalBodyKicksMake": 0,
        "TotalBodyKicksThrown": 0,
        "TotalClinchStrikesMade": 0,
        "TotalClinchStrikesThrown": 0,
        "TotalElbowsMade": 0,
        "TotalElbowsThrown": 0,
        "TotalGroundStrikesMade": 0,
        "TotalGroundStrikesThrown": 0,
        "TotalHighKicksMade": 0,
        "TotalHighKicksThrown": 0,
        "TotalHooksMade": 0,
        "TotalHooksThrown": 0,
        "TotalJabsMade": 0,
        "TotalJabsThrown": 0,
        "TotalKicksLanded": 0,
        "TotalKicksThrown": 0,
        "TotalLegKicksMade": 0,
        "TotalLegKicksThrown": 0,
        "TotalOverhandsMade": 0,
        "TotalOverhandsThrown": 0,
        "TotalPunchesLanded": 0,
        "TotalPunchesThrown": 0,
        "TotalSpinBackFistsMade": 0,
        "TotalSpinBackFistsThrown": 0,
        "TotalStraightsMade": 0,
        "TotalStraightsThrown": 0,
        "TotalStrikesLanded": 0,
        "TotalUppercutsMade": 0,
        "TotalUppercutsThrown": 0,
        "TripTakedownAttempts": 0,
        "TwisterAttempts": 0,
        "UppercutsAbsorbed": 0,
        "VonFlueAttempt": 0,
        "WinsVsOrthodox": 0,
        "WinsVsSouthpaw": 0,
        "WinsVsSwitch": 0,
        }

x = mycol.insert_one(mydict)